// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwgjloeygeibfuctabhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3Z2psb2V5Z2VpYmZ1Y3RhYmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjg2NTUsImV4cCI6MjA2Njg0NDY1NX0.DLwpjNYHqd1URIcEXVBCksIAxdO3WosTxK11DFhNkBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});